name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write
  contents: write
  deployments: write
  pages: write
  statuses: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        if: github.event_name == 'push'
        run: |
          if [ -z "$deploy_key" ]
          then
            echo "You do not have a secret named SSH_DEPLOY_KEY.  This means you did not follow the setup instructions carefully.  Please try setting up your repo again with the right secrets."
            exit 1;
          fi
        env:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Copy Repository Contents
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify the Ruby version needed

      - name: Install Dependencies
        run: bundle install

      - name: Build the Jekyll Site
        run: bundle exec jekyll build

      - name: copy CNAME file into _site if CNAME exists
        run: |
          sudo chmod -R 777 _site/
          cp CNAME _site/ 2>/dev/null || :

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_dir: ./_site
